using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TestForBart.Migrations
{
    /// <inheritdoc />
    public partial class MakeIncidentNameAutogenerated : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Incidents",
                type: "nvarchar(450)",
                nullable: false,
                defaultValueSql: "'Incident_'+convert(varchar,getdate(),25)",
                oldClrType: typeof(string),
                oldType: "nvarchar(450)");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Incidents",
                type: "nvarchar(450)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(450)",
                oldDefaultValueSql: "'Incident_'+convert(varchar,getdate(),25)");
        }
    }
}
